name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Automatic merge
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout ${{ github.event.pull_request.head.ref }}
          git merge ${{ github.event.pull_request.base.ref }} --no-edit
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
